Configuration based TUDelft calculation
os-climate/physrisk pull request #353
Opened 2024-09-18 11:28 UTC by joemoorhouse

Finish changes related to running a flood calculation using TUDelft data, including standard of protection, and using configuration-based vulnerability.
Partial implementation of vulnerability function uncertainty in config-based models and add to docs.

2024-09-18 13:30 UTC, xbarra requested changes
Please, rebase this branch onto main before merging.

2024-09-19 07:05 UTC, xbarra requested changes
I would rather this got moved to it's own pr and merged.

Also a part of a bigger conversation, but squashing it on this merge would make it difficult to track

2024-09-19 14:00 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +class ImpactCurve:
Missing docstring in public class(fails Ruff rule D101)

2024-09-19 14:00 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def __init__(
Missing docstring in __init__ (fails Ruff rule D107)

2024-09-19 14:01 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def get_impact(self, points_x: np.ndarray) -> np.ndarray: ...
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:01 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def get_impact_curve(item: VulnerabilityConfigItem):
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:01 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +class PiecewiseLinearImpactCurve(ImpactCurve):
Missing docstring in public class(fails Ruff rule D101)

2024-09-19 14:02 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +class ParametricImpactCurve(ImpactCurve):
Missing docstring in public class(fails Ruff rule D101)

2024-09-19 14:03 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def get_impact(self, points_x: np.ndarray) -> np.ndarray:
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:03 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def __init__(
Missing docstring in init (fails Ruff rule D107)

2024-09-19 14:04 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_impact_curves.py
> +    def get_impact(self, points_x: np.ndarray) -> np.ndarray:
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:04 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_acute.py
> +from typing import (
Missing docstring in public module (fails Ruff rule D100).

2024-09-19 14:05 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_acute.py
> +class ConfigBasedVulnerabilityModelAcute(VulnerabilityModelAcuteBase):
Missing docstring in public class (fails Ruff rule D101)

2024-09-19 14:06 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_acute.py
> +        """A vulnerability model that requires only specification of a set of damage/disruption curves
1 blank line required between summary line and description  (fails Ruff rule D205)

First line of docstring should be in imperative mood: "A vulnerability model that requires only specification of a set of damage/disruption curves" (fails Ruff rule D401)

2024-09-19 14:07 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_acute.py
> +    def get_data_requests(
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:07 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_acute.py
> +    def get_distributions(
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:09 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_param.py
> +from typing import (
Missing docstring in public module (fails Ruff rule D100).

2024-09-19 14:09 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_param.py
> +class ConfigBasedVulnerabilityModel(VulnerabilityModelBase):
Missing docstring in public class (fails Ruff rule D101)

2024-09-19 14:12 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_param.py
> +        """A vulnerability model that requires only specification of a set of damage/disruption curves
1 blank line required between summary line and description (fails Ruff rule D205)
First line of docstring should be in imperative mood: "A vulnerability model that requires only specification of a set of damage/disruption curves" (fails Ruff rule D401)

2024-09-19 14:13 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_param.py
> +    def get_data_requests(
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:14 UTC, VMarfima commented on src/physrisk/vulnerability_models/config_based_vuln_model_param.py
> +    def get_impact(
Missing docstring in public method (fails Ruff rule D102)

2024-09-19 14:18 UTC, VMarfima commented on tests/data/hazard_model_store_test.py
> +        index_values: Union[List[float], npt.NDArray, List[str]] = [0.0],
Do not use mutable data structures for argument defaults (fails Ruff rule B006).

2024-09-19 14:19 UTC, VMarfima commented on tests/data/hazard_model_store_test.py
> +        index_values: Union[List[float], npt.NDArray, List[str]] = [0.0],
Do not use mutable data structures for argument defaults (fails Ruff rule B006).

2024-09-19 14:26 UTC, VMarfima commented on docs/user-guide/vulnerability_uncertainty.ipynb
> +    "fig.add_scatter(x=interp[0, :], y=vuln.impact, name=f\"Interpolated depth 0.6m\")\n",
f-string without any placeholders (fails Ruff rule F541).

2024-09-22 14:40 UTC, joemoorhouse commented
Hi @xbarra and @VMarfima,
Thanks for comments; as suggested I pulled out the PDM lock update into a separate PR and rebased. I took the change to add the PDM matrix CI at the same time.

A couple of changes that hit a lot of files:
1) Change of Type hint in vulnerability models from Iterable[HazardDataResponse] to Sequence[HazardDataResponse]. Probably should have been like this in the first place (not really intent to allow for generators here and length should be known), but had a case with the config-based models where it was desirable to see length of responses hence change in this PR. I also addressed some other Type hints, generally preferring Sequence over List.
Hopefully does not affect too much and straight forward to change; no good time to make such changes.
2) Starting to address some of the ruff excluded items I removed exclusion for unused imports.

Added some more doc strings, but still more to do there.

Thanks,
Joe

2024-09-22 14:42 UTC, merged